version: "3.7"

services:
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    networks:
      - nginx_network
      - webapp_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mywebapp1
      - mywebapp2

  mywebapp1:
    build:
      dockerfile: ./Dockerfile
    expose:
      - "1501"
    container_name: mywebapp1
    networks:
      - webapp_network
  mywebapp2:
    build:
      dockerfile: ./Dockerfile
    container_name: mywebapp2  
    expose:
      - "1501"
    networks:
      - webapp_network
networks:
  nginx_network:
    external: true
  webapp_network:
    external: false
